### PR TITLE
Alternative impl for MessagePack + Lua

### PR DESCRIPTION
**Pull request by badtuple**
@AndrewScibek this is the simpler implementation of including MessagePack...but it seems like there's a major bug in the MessagePack implementation, or at least how it interacts with the rlua-serde package.

I like how simple this is, but if we can't find the bug and get it merged upstream, the options imo are:

- Keep going with the custom impl in the other PR
- Switch to another serialization format. JSON is the one that'll be easiest to work with and is most widely understood...but it bugs me that there isn't proper Integer support and you can't send raw binary.

### CODE REVIEW

**Comment by AndrewScibek** [comment]
> @AndrewScibek this is the simpler implementation of including MessagePack...but it seems like there's a major bug in the MessagePack implementation, or at least how it interacts with the rlua-serde package.
> 
> I like how simple this is, but if we can't find the bug and get it merged upstream, the options imo are:
> 
>     * Keep going with the custom impl in the other PR
> 
>     * Switch to another serialization format. JSON is the one that'll be easiest to work with and is most widely understood...but it bugs me that there isn't proper Integer support and you can't send raw binary.

Wow this impl is so much cleaner and understandable. I know you spent a lot of time of the other pr but this seems way more maintainable. 

On the issue of switching from msgpack, the main downside is we would put the effort on the end user if they want to send binary stuff(encode base64 or w/e) and ints arent ints?

**Comment by badtuple** [comment]
Yeah, the main downsides are not having proper Integers and not supporting raw binary.

Proper Integer support I think is pretty important for a database. Floating point provides alot of footguns to be automatically opted-in to.  Many operations, like division for example, is just fundamentally different.

Binary support is mainly important due to space. Since we're looking at Logs on disk, less space means faster seeking/iteration. I don't mind the user (really the client) knowing to convert to base64, but I do mind having the same data be 33% larger than it has to be because base64 only uses 64 possible values per byte instead of 256.

The rest of the overhead of JSON vs MessagePack can be mitigated with compression schemes, but while we can compress JSON, arbitrary Base64 data really doesn't compress as well.

**Comment by badtuple** [comment]
Also I definitely agree on this being more maintainable. I'd much prefer it to the other route for message pack if we can get it to work.  I think I'd prefer the other route to using JSON long term though.

**Comment by badtuple** [comment]
Closing because we moved to CBOR from MessagePack

**Pull request closed without merging**
